name: "Publish to Docker"
description: "Build a container image and Pushes it to Docker registry"

inputs:
  username:
    description: "Username for image registry"
    required: true
  password:
    description: "Password for image registry"
    required: true
 tags:
    description: "How to tag the image. Default: latest"   
    
runs:
  using: "composite"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry tomlkit
      - name: Update version in pyproject.toml
        run: |
          VERSION=${inputs.tags}
          python -c "import tomlkit; p = tomlkit.parse(open('pyproject.toml').read()); p['tool']['poetry']['version'] = '$VERSION'; open('pyproject.toml', 'w').write(tomlkit.dumps(p))"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add pyproject.toml
          git commit -m "Update version"
          git push

      - name: build image and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: viniciusfca
          password: ${{inputs.DOCKER_PASSWORD}}
          repository: viniciusfca/cepapi
          tags: ${{ inputs.tags }}, lastest
