name: "Publish to Docker"
description: "Build a container image and Pushes it to Docker registry"

inputs:
  username:
    description: "Username for image registry"
    required: true
  password:
    description: "Password for image registry"
    required: true
  tag: 
    description: "How to tag the image. Default: latest"    
    
runs:
  using: "composite"
  steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        run: | 
          pip install toml
          python -c "import toml; data = toml.load('pyproject.toml'); data['tool']['poetry']['version'] = '${{inputs.tag}}'; toml.dump(data, open('pyproject.toml', 'w'))"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add pyproject.toml
          git commit -m "Update version to ${{inputs.tag}}}"
          git push
          
      - name: Setup Build
        uses: docker/setup-buildx-action@v1

      - name: Login to the Registry
        uses: docker/login-action@v1
        with:
          username: ${{inputs.username}}
          password: ${{inputs.password}}
      
      - name: Set the tag
        shell: bash
        run: |
          if [ -z "${{inputs.tag}}" ]
          then
            echo "final_tag=latest" >> $GITHUB_ENV
          else
            echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
          fi
      
      - name: Build and Push the Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: viniciusfca/cepapi:${{env.final_tag}}
